### ISSUE TITLE
nrfMicro 1.1 doesn't detects via USB, possible duplication of #37

### ISSUE THREAD

**Issue by Raskilas** [joric/nrfmicro#41]
Hi, it is me again). It have a similiar symptoms, but I gathered more details, I can augment #37 if it necessary.
I've got Bluepill from Aliexpress and it have **CKS32F103C8T6** chip. I've used UART module with [STM32 Flash loader demonstrator](https://www.st.com/en/development-tools/flasher-stm32.html) to upgrade it. 

I've checked nrfMicro according to the method described in wiki [Testing](https://github.com/joric/nrfmicro/wiki/Soldering#testing) and I've got 3.3V on VCC, 4.2V between B- and B+, ~5.2V on USB-C power pin, and have voltage drop 0.6-1.1V on almost all pads. Voltage drop also exist 0.6-1.1V between B- and E73 backpads and soldered components (except cases when some of them have direct/short connection like antenna or E73 shield), but couple resistors shows, I think, off scale values (may be it is the cause). Red LED is glowing when I plug nrfMicro to USB port. After soldering nrfMicro doesn't recognizable via USB - is it correct?

I tried to flash E73 on linux and here is what I have:
![nrfMicro1 1_flashing_linux](https://user-images.githubusercontent.com/1936631/116320411-dee45f00-a7c0-11eb-9bdd-b888ce5295f3.png)

1) So is there any advice of what I can check additionally or what should I do? 
2) May be I should find Bluepill with STM... chip instead of CKS...? 
3) Do you have a some reference map, so I could check drop of voltage between all solder contacts/fields?
4) Is unlocking and flashing of E73 completed successfully?

**Comment by joric** [comment]
* New unflashed chip does not work with USB, because well, there's no firmware.
* Bootloader has been flashed correctly, according to the Big Picture, so normally it pops up USB drive right away.
* I don't have methodology for checking out badly soldered USB connector. Just check that all USB pins are soldered. That includes VBUS, CC1, CC2, and D+ D- pins, they all should go where they belong and should not be shorted to each other.
